### PR TITLE
Use Pandas.

### PR DESCRIPTION
**Pull request by airalcorn2**
Hey, @mbevand. Thanks a lot for your script! I made some changes that made it a little easier for me to follow along with what you were doing. Basically, I compute all of the statistics in Pandas (and use Pandas to directly load the CSV from the URL, eliminating the manual download step) and use f-strings in all of the print statements. I also generate a second heat map that shows how the distribution of cases changes over time. Feel free to ignore, but wanted to pass the script along in case you found any of it useful.

percent_over_time

### CODE REVIEW

**Comment by mbevand** [comment]
Cool, thanks for the many improvements! I'll take a look. One minor complaint is that now every time the script is run, it downloads an 18MB CSV file. pandas's urllib doesn't even request gzip compression. Maybe if a file is specified on the command line the script could pick it up instead of downloading the data.

**Comment by airalcorn2** [comment]
Good idea. The user now has the option to provide the path to the CSV as a command line argument.

**Comment by psifertex** [comment]
The hard-coded csv URL will be stuck with old data unless you request the latest URL by first processing https://open-fdoh.hub.arcgis.com/datasets/florida-covid19-case-line-data

Or consider using the json interface, though at first glance it appears limited to 2000 entries

**Comment by mbevand** [comment]
I've been monitoring and downloading data on a daily bases, and in my experience the hardcoded CSV url doesn't change. We can fix it if it changes.

Thanks airalcorn2, merged! I'll probably end up deleting my old code and renaming simplified.py to process.py

**Comment by psifertex** [comment]
Ahh, I think I was still looking at the `_published` file which is why I wasn't seeing the new data. Yup, the url looks stable sorry about that!

**Comment by mbevand** [comment]
@airalcorn2 I replaced my main script with yours and made slight changes here and there.
I also credited you in the README.md, let me know if that's ok

**Comment by airalcorn2** [comment]
Cool! Thanks a lot, @mbevand! And thanks again for the original script!

**Pull request merged**
